# Generated by Django 5.2.1 on 2025-05-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('Phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField()),
                ('Date', models.DateField(auto_now=True)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_book_app.student')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score_book_app.subject')),
            ],
        ),
    ]
