# Generated by Django 5.2.1 on 2025-05-16 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
    ]
