# Generated by Django 5.2.1 on 2025-05-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_book_app', '0002_rename_email_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
